#
# Version 1

# Pull from fedora Base Image
FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal

MAINTAINER Scott McCarty smccarty@redhat.com

# Update the image
RUN yum -y install nmap-ncat;yum clean all
RUN echo "Hi! I'm a database. Get in ma bellie!!!" > /srv/hello.txt


# Output
# ENTRYPOINT tail /var/log/yum.log
