#
# Version 1

# Pull from fedora Base Image
FROM registry.access.redhat.com/ubi7-dev-preview/ubi-minimal

MAINTAINER Scott McCarty smccarty@redhat.com

# Update the image
RUN microdnf --enablerepo=rhel-7-server-rpms install -y nmap-ncat
RUN echo "Hi! I'm a database. Get in ma bellie!!!" > /srv/hello.txt

# Output
EXPOSE 3306
CMD bash -c 'while true; do /usr/bin/nc -l -p 3306 < /srv/hello.txt; done'
